name: Hello World!

on:
  push:
    branches:
      - master

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
          echo "Hello World2!"
      - name: Now it is
        run: |
          date
      - name: Directory content
        run: ls -l
